### ISSUE TITLE
Use avrdude option "-C +"

### ISSUE THREAD

**Issue by pischky** [onandoffables/avrdude-linuxgpio#1]
Using "avrdude -C +extra-config-file" would be much easier and would not depend
on installed version of avrdude.

See
https://www.nongnu.org/avrdude/user-manual/avrdude_3.html
search for "-C config-file"

**Comment by onandoffables** [comment]
Thanks. On the Raspberry Pi we do actually need a specific version of avr-dude that's compiled with `--enable-linuxgpio=yes`. That's what the `compile_avrdude.sh` script in this repo does.
The patching of the default config file is just provided as a free bonus here. The `-C config-file` option still works.

**Comment by pischky** [comment]
On current raspios avrdude is compiled with gpio support.
Just do "apt install avrdude" to get version 6.3.

**Comment by rktrlng** [comment]
That is great news. A newer version as well.
Thanks again!
